version: '3.8'
services:
  api:
    image: docker-java-jar
    ports:
      - '8888:8888'
  ui:
    image: docker-react
    ports:
      - '3006:3005'
    volumes:
      - ./ui/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/public/index.html:/usr/share/nginx/html/index.html
      - ./ui/public/css:/usr/share/nginx/html/css
