version: '3.8'
services:
  api:
    container_name: docker-java-jar
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
  ui:
    container_name: docker-react
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '9000:3005'
    volumes:
      - ./ui/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/public/index.html:/usr/share/nginx/html/index.html
      - ./ui/public/css:/usr/share/nginx/html/css
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'