server:
  port: 8888

logging:
  config: classpath:logback-spring.xml

cors:
  allow: true

spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: 'postgres'
    password: 'postgres'
    url: 'jdbc:postgresql://db:5432/documents' #'jdbc:postgresql://localhost:5432/documents'
  liquibase:
    change-log: classpath:migrations/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  kafka:
    bootstrap-servers: kafka:29092 #localhost:29093

documents:
  topic:
    documents-in: "documents-in"
    documents-out: "documents-out"
